### ISSUE TITLE
"npm run build" error

### ISSUE THREAD

**Issue by hassanayoub1985** [Ninja-21-dev/matrix-ranobot-readme#1]
![image](https://user-images.githubusercontent.com/26030596/208035576-27a54767-3a1e-4217-8907-cca8518ae249.png)

**Comment by Ninja-21-dev** [comment]
![image](https://user-images.githubusercontent.com/101307554/208140022-bf830e49-98ec-43f3-889c-87a3aeff382a.png)

**Comment by hassanayoub1985** [comment]
For sure sure I did all that, do I record that as a movie for you?
